package de.sinnix.judoturnier.model;

public enum Wettkampfsystem {
	KEIN_WETTKAMPF,
	BESTER_AUS_DREI,
	JEDER_GEGEN_JEDEN,
	ZWEI_POOLS_JEDER_GEGEN_JEDEN,
	DOPPELTES_KO_SYSTEM_MIT_TROSTRUNDE,
	BRASILIANISCHES_KO_SYSTEM_MIT_DOPPELTER_TROSTRUNDE,
	VORGEPOOLTES_KO_SYSTEM,
	KO_SYSTEM_MIT_DOPPELTER_TROSTRUNDE,
	POOLSYSTEM_JEDER_GEGEN_JEDEN
}
