image: python:3.9  # Basis-Image mit Python für Ansible

stages:
  - build
  - deploy

before_script:
  - pip install ansible  # Installiere Ansible für CI/CD

build-app:
  stage: build
  script:
    - ansible-playbook -i localhost, -c local deployment/playbook.yml --tags "build"
  tags:
    - default-docker-runner
  artifacts:
    paths:
      - /tmp/springboot-app.tar  # Docker-Image für Deploy sichern

deploy-app:
  stage: deploy
  script:
    - ansible-playbook -i deployment/inventory.yml deployment/playbook.yml --tags "deploy"
  tags:
    - default-docker-runner
