version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    container_name: postgres-judo
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5532:5432
    networks:
      - net
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  turnier-service:
    container_name: turnierservice-judo
    build:
      context: .
      dockerfile: Dockerfile
    image: turnier-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak-judo
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
    ports:
      - 7080:8080
      - 7443:7443
    depends_on:
      - db
    networks:
      - net
    restart: always
