networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres-judo-java
    ports:
      - "5532:5432"
    expose:
      - 5432
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - net
    restart: unless-stopped