CREATE TABLE begegnung (
                           id SERIAL,
                           wettkaempfer1 INTEGER,
                           wettkaempfer2 INTEGER,
                           altersklasse VARCHAR(255),
                           strafenWettkaempfer1 INTEGER,
                           punkteWettkaempfer1 INTEGER,
                           strafenWettkaempfer2 INTEGER,
                           punkteWettkaempfer2 INTEGER,
                           sieger INTEGER,
                           zeit INTEGER,
                           kampfgeistWettkaempfer1 INTEGER,
                           technikWettkaempfer1 INTEGER,
                           kampfstilWettkaempfer1 INTEGER,
                           fairnessWettkaempfer1 INTEGER,
                           kampfgeistWettkaempfer2 INTEGER,
                           technikWettkaempfer2 INTEGER,
                           kampfstilWettkaempfer2 INTEGER,
                           fairnessWettkaempfer2 INTEGER,
                           PRIMARY KEY (id)
);