spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    hikari:
      # Optional: These settings optimize HikariCP for testing scenarios
      maximum-pool-size: 2
      pool-name: HikariTestPool

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            client-secret: test-secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: https://dummy-oauth2-provider/auth
            token-uri: https://dummy-oauth2-provider/token
            user-info-uri: https://dummy-oauth2-provider/userinfo
            user-name-attribute: sub
