spring:
    application.name: judoturnier

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    flyway:
        enabled: true
        locations: classpath:db
        baseline-on-migrate: true
        validate-on-migrate: true